spring:
  application:
    name: tink-api-with-charts
  datasource:
    url: jdbc:sqlite:spread_history.db
    driver-class-name: org.sqlite.JDBC
    jpa:
      database-platform: org.hibernate.community.dialect.SQLiteDialect
      hibernate:
        ddl-auto: update
      show-sql: true

#logging:
#  level:
#    com.github.tink_api_with_charts: DEBUG
#    ru.ttech.piapi: INFO

invest:
  connector:
    #    sandbox
    token: abc
    sandbox:
      enabled: true
    grpc:
      debug: false

##    share-uid: "87db07bc-0e02-4e29-90bb-05e8ef791d7b" # T
##    future-uid: "12275713-0583-4add-a4a5-c7dd234d4f34" # TBM6
#
#    share-uid: "de82be66-3b9b-4612-9572-61e3c6039013" # TGLD
#    future-uid: "b347fe28-0d2a-45bf-b3bd-cda8a6ac64e6" # GLDRUBF

trading:
  bot:
    lots: 2
    balance: 1_000_000
    # Конфигурация списка пар инструментов (новый формат)
    # Пример для нескольких пар:
    pairs:
      - name: "SBER-SBERF"
        shareUid: "e6123145-9665-43e0-8413-cd61b8aa9b13"
        futureUid: "9e9c5921-43ac-47a8-b537-ccf32ebc6da3"
        futureLot: 1
      - name: "GAZP-GAZPF"
        shareUid: "962e2a95-02a9-4171-abd7-aa198dbe643a"
        futureUid: "82b34e5c-30c3-4be2-ba9d-5ba3b37ca99b"
        futureLot: 1